*** Settings ***
Documentation    Resource file containing test data for flight and passenger IDs used in airline automation tests.


*** Variables ***
${TEST_FLIGHT_SCHEDULED_ID}      1179217
${TEST_FLIGHT_BOARDING_ID}       1179218
${TEST_FLIGHT_DEPARTED_ID}       1179219
${TEST_FLIGHT_CANCELLED_ID}      1179220
${TEST_PASSENGER_ID}             1382664
${TEST_PASSENGER_EMAIL}          harry@hogwarts.com
${TEST_PASSENGER_FIRST}          Harry
${TEST_PASSENGER_LAST}           Potter
