name: Robot Framework Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Install Chrome
      uses: browser-actions/setup-chrome@v1

    - name: Clone Django project
      run: git clone https://github.com/Lekkioui/airline-django.git

    - name: Setup DB + Data + Run Tests
      run: |
        cd airline-django

        # Reset DB
        rm -f db.sqlite3
        python manage.py migrate

        # Create admin user
        python manage.py shell -c "
        from django.contrib.auth.models import User;
        User.objects.create_superuser('anasse', 'anasse@gmail.com', 'anasse123') if not User.objects.filter(username='admin').exists() else None
        "

        # Run server
        python manage.py runserver &
        sleep 5

        cd ..
        robot tests/