name: Robot Framework Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Install Chrome
      uses: browser-actions/setup-chrome@v1

    - name: Clone Django project
      run: git clone https://github.com/Lekkioui/airline-django.git

    - name: Setup DB + Run App + Execute Tests
      run: |
        cd airline-django

        # Reset DB propre
        rm -f db.sqlite3
        python manage.py migrate

        # Lancer serveur en arrière-plan
        python manage.py runserver &

        # Attendre que le serveur démarre
        sleep 5

        # Revenir au repo principal
        cd ..

        # Lancer les tests
        robot tests/